---
- name: Run playbook
  hosts: localhost
  gather_facts: false
  vars_files:
    - vars/vars.yml
  tasks:
    - name: Setup VPC
      ansible.builtin.import_role:
        name: vpc
        tasks_from: vpc_task.yml

    # - name: Get AMI ID
    #   import_role:
    #     name: ec2
    #     tasks_from: get_latest_ami_id.yml
    # TODO: Fix module returning incorrect ami id


    # TODO: setup ssl certs
    - name: Launch ec2
      ansible.builtin.include_role:
        name: ec2
        tasks_from: create_ec2_task.yml
      vars:
        ec2_instance_type: "{{ item.instance_type }}"
        ec2_security_group: "{{ vpc_sg.group_id }}"
        # ec2_subnet_id:
        # "{{ aza_apse2.subnet.id if item.subnet_az == 'a'
        # else azb_apse2.subnet.id if item.subnet_az == 'b'
        # else azc_apse2.subnet.id if item.subnet_az == 'c' }}"
        ec2_subnet_id: "{{ aza_apse2.subnet.id }}" # putting it all in one since running out of time to dynamically generate subnet ids inline
        ec2_ami_id: "{{ ami_id }}"
        ec2_name: "{{ item.name }}"
        ec2_key_name: "{{ key_pair_name }}"
      with_items: "{{ ec2_instances }}"

    - name: List items in inventory
      ansible.builtin.debug:
        msg: "{{ item }}"
      loop: "{{ groups['all'] }}"
