- name: Create vpc
  amazon.aws.ec2_vpc_net:
    name: "{{ common_name }}"
    cidr_block: "{{ vpc_cidr }}"
    region: "{{ aws_region }}"
  register: vpc

- name: Create subnet for first az
  amazon.aws.ec2_vpc_subnet:
    vpc_id: "{{ vpc.vpc.id }}"
    state: present
    az: "{{ aws_region }}a"
    cidr: "{{ vpc_subnet_a_cidr }}"
    tags: {"Name": "{{ common_name }}_az_a"}
  register: aza_apse2

- name: Create subnet for second az
  amazon.aws.ec2_vpc_subnet:
    vpc_id: "{{ vpc.vpc.id }}"
    state: present
    az: "{{ aws_region }}b"
    cidr: "{{ vpc_subnet_b_cidr }}"
    tags: {"Name": "{{ common_name }}_az_b"}
  register: azb_apse2

- name: Create subnet for third az
  amazon.aws.ec2_vpc_subnet:
    vpc_id: "{{ vpc.vpc.id }}"
    state: present
    az: "{{ aws_region }}c"
    cidr: "{{ vpc_subnet_c_cidr }}"
    tags: {"Name": "{{ common_name }}_az_c"}
  register: azc_apse2

- name: Create internet gateway
  amazon.aws.ec2_vpc_igw:
    vpc_id: "{{ vpc.vpc.id }}"
    state: present
    tags: {"Name": "{{ common_name }}_igw"}
  register: igw

- name: Create custom route table
  amazon.aws.ec2_vpc_route_table:
    vpc_id: "{{ vpc.vpc.id }}"
    region: ap-southeast-2
    subnets:
      - "{{ aza_apse2.subnet.id }}"
      - "{{ azb_apse2.subnet.id }}"
      - "{{ azc_apse2.subnet.id }}"
    routes:
      - dest: 0.0.0.0/0
        gateway_id: "{{ igw.gateway_id }}"
    tags: {"Name": "{{ common_name }}_rtb"}

- name: Create security group
  amazon.aws.ec2_security_group:
    name: "{{ common_name }}_ssh_http"
    description: allow ssh and http
    vpc_id: "{{ vpc.vpc.id }}"
    region: "{{ aws_region }}"
    rules:
      - proto: tcp
        ports: 22
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        ports: 80
        cidr_ip: 0.0.0.0/0
  register: vpc_sg
